name: desktop_toolkit
description: Fuck Great Firewall.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.10.0
  fluentui_system_icons: ^1.1.273
  json_annotation: ^4.9.0
  file_picker: ^8.3.1
  path_provider: ^2.1.5
  path: ^1.9.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14

build_runner:
  targets:
    - name: desktop_toolkit
      module: package:desktop_toolkit/main.dart
      output: lib/main.g.dart


flutter:
  uses-material-design: true
